# -*- coding: utf-8 -*-
"""YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7aBoIR1Yho8UaJS4D5McdSSSG6IHDUp
"""

!nvidia-smi

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ttWbac1mt33JDGyBIpEk")
project = rf.workspace("dmart").project("retail-store-india-new-2-sfaqi")
version = project.version(1)
dataset = version.download("yolov12")

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
from ultralytics import YOLO


model = YOLO("yolo11m.pt")


results = model.train(data="/content/Retail-Store-India-New-2-1/data.yaml", epochs=100, imgsz=640)

from ultralytics import YOLO


model = YOLO("yolov10s.yaml")


results = model.train(data="/content/Retail-Store-India-New-2-1/data.yaml", epochs=100, imgsz=640)

from ultralytics import YOLO


model = YOLO("yolov10m.yaml")


results = model.train(data="/content/Retail-Store-India-New-2-1/data.yaml", epochs=100, imgsz=640)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Retail-Store-India-New-2-1
import time
import torch
from ultralytics import YOLO

model = YOLO("best12.pt")
img = "/content/Retail-Store-India-New-2-1/train/images/20231113_153350-2_jpg.rf.043d4cad25fb570fdf175537b8ee7f52.jpg"

# Warmup
for _ in range(10):
    _ = model(img)

# Benchmark
t0 = time.time()
for _ in range(100):
    _ = model(img)
t1 = time.time()

latency = (t1 - t0) / 100 * 1000  # ms/img
print(f"Latency: {latency:.2f} ms/img")

from ultralytics import YOLO

# Load your model
model = YOLO("best08.pt")

# Run validation
metrics = model.val(data="/content/Retail-Store-India-New-2-1/data.yaml")

# Extract mAP values
print("mAP@50:", metrics.box.map50)       # IoU=0.50
print("mAP@50-95:", metrics.box.map)      # IoU=0.50:0.95 (COCO style)
print("Precision:", metrics.box.mp)
print("Recall:", metrics.box.mr)





